[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  timeout = 26

[[redirects]]
  from = "/api/gemini"
  to = "/.netlify/functions/gemini"
  status = 200

[[redirects]]
  from = "/api/gemini-image"
  to = "/.netlify/functions/gemini-image"
  status = 200

[[redirects]]
  from = "/api/gemini-audio"
  to = "/.netlify/functions/gemini-audio"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200